### ISSUE TITLE
UnsupportedOperationException: error in table model that cannot be fixed automatically

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#120]
```
2017-10-10 16:32:18,202 [INFO ] com.xmlcalabash.runtime.XAtomicStep - bundle://61.0:0/xml/css-to-obfl.xpl:574:35:Property orphans not supported inside table cell elements
2017-10-10 16:32:18,202 [DEBUG] o.e.persistence.logging.default - Connection(1074614461)--Thread(Thread[Thread-16256,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:32:18,203 [INFO ] com.xmlcalabash.runtime.XAtomicStep - bundle://61.0:0/xml/css-to-obfl.xpl:574:35:Property widows not supported inside table cell elements
2017-10-10 16:32:18,203 [DEBUG] o.e.persistence.logging.default - Connection(283993068)--Thread(Thread[Thread-16256,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:32:18,235 [INFO ] com.xmlcalabash.runtime.XAtomicStep - bundle://61.0:0/xml/css-to-obfl.xpl:574:35:Property orphans not supported inside table cell elements
2017-10-10 16:32:18,236 [DEBUG] o.e.persistence.logging.default - Connection(1039311668)--Thread(Thread[Thread-16256,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:32:18,237 [INFO ] com.xmlcalabash.runtime.XAtomicStep - bundle://61.0:0/xml/css-to-obfl.xpl:574:35:Property widows not supported inside table cell elements
2017-10-10 16:32:18,238 [DEBUG] o.e.persistence.logging.default - Connection(671749880)--Thread(Thread[Thread-16256,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:32:18,239 [INFO ] com.xmlcalabash.runtime.XAtomicStep - bundle://61.0:0/xml/css-to-obfl.xpl:574:35:Property orphans not supported inside table cell elements
2017-10-10 16:32:18,239 [DEBUG] o.e.persistence.logging.default - Connection(1800104967)--Thread(Thread[Thread-16256,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:32:18,240 [INFO ] com.xmlcalabash.runtime.XAtomicStep - bundle://61.0:0/xml/css-to-obfl.xpl:574:35:Property widows not supported inside table cell elements
2017-10-10 16:32:18,240 [DEBUG] o.e.persistence.logging.default - Connection(153084372)--Thread(Thread[Thread-16256,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:32:18,574 [DEBUG] c.xmlcalabash.library.LabelElements - Running label-elements !1.37
2017-10-10 16:32:19,298 [DEBUG] com.xmlcalabash.library.Delete - Running delete !1.38
2017-10-10 16:32:19,404 [DEBUG] com.xmlcalabash.library.AddAttribute - Running add-attribute !1.39
2017-10-10 16:32:19,512 [DEBUG] com.xmlcalabash.library.Identity - Running identity _1
2017-10-10 16:32:19,514 [DEBUG] com.xmlcalabash.library.Insert - Running insert !1.40.2
2017-10-10 16:32:19,620 [DEBUG] com.xmlcalabash.library.Delete - Running delete !1.40.3
2017-10-10 16:32:19,733 [DEBUG] com.xmlcalabash.library.XSLT - Running xslt !1.3
2017-10-10 16:32:19,939 [DEBUG] com.xmlcalabash.library.Identity - Running identity !1.19.1.1.1
2017-10-10 16:32:19,939 [DEBUG] com.xmlcalabash.library.DefaultStep - Running {http://code.google.com/p/dotify/}obfl-to-pef !1.19.1.2
2017-10-10 16:32:23,103 [ERROR] o.d.p.b.d.c.impl.OBFLToPEFStep - dotify:obfl-to-pef failed
java.lang.UnsupportedOperationException: There's an error in the table model that cannot be fixed automatically. Go back to the source and correct any errors in the table.
	at org.daisy.dotify.formatter.impl.TableData.completeRow(TableData.java:117) ~[na:na]
	at org.daisy.dotify.formatter.impl.TableData.closeTable(TableData.java:80) ~[na:na]
	at org.daisy.dotify.formatter.impl.Table.closeTable(Table.java:53) ~[na:na]
	at org.daisy.dotify.formatter.impl.FormatterCoreImpl.endTable(FormatterCoreImpl.java:492) ~[na:na]
	at org.daisy.dotify.obfl.ObflParser.parseTable(ObflParser.java:1032) ~[na:na]
	at org.daisy.dotify.obfl.ObflParser.parseSequence(ObflParser.java:573) ~[na:na]
	at org.daisy.dotify.obfl.ObflParser.parse(ObflParser.java:143) ~[na:na]
	at org.daisy.dotify.engine.impl.LayoutEngineImpl.convert(LayoutEngineImpl.java:109) ~[na:na]
	at org.daisy.pipeline.braille.dotify.calabash.impl.OBFLToPEFStep.run(OBFLToPEFStep.java:136) ~[na:na]
	at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:389) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XChoose.run(XChoose.java:135) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at com.xmlcalabash.extensions.Eval.run(Eval.java:249) ~[na:na]
	at org.daisy.pipeline.braille.common.calabash.impl.PxTransformStep.run(PxTransformStep.java:143) ~[na:na]
	at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:389) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XChoose.run(XChoose.java:135) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at com.xmlcalabash.runtime.XPipelineCall.run(XPipelineCall.java:94) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:242) ~[na:na]
	at org.daisy.pipeline.job.Job.run(Job.java:216) ~[na:na]
	at org.daisy.pipeline.job.impl.DefaultJobExecutionService$1.run(DefaultJobExecutionService.java:113) ~[na:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
2017-10-10 16:32:23,103 [ERROR] com.xmlcalabash.runtime.XAtomicStep - bundle://61.0:0/xml/transform/dotify-transform.xpl:62:37:java.lang.UnsupportedOperationException: There's an error in the table model that cannot be fixed automatically. Go back to the source and correct any errors in the table.
2017-10-10 16:32:23,104 [DEBUG] o.e.persistence.logging.default - Connection(1680795282)--Thread(Thread[Thread-16256,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:32:23,105 [DEBUG] o.a.h.i.c.PoolingClientConnectionManager - Connection manager is shutting down
2017-10-10 16:32:23,105 [DEBUG] o.a.h.i.c.PoolingClientConnectionManager - Connection manager shut down
2017-10-10 16:32:23,105 [ERROR] com.xmlcalabash.runtime.XAtomicStep - bundle://61.0:0/xml/transform/dotify-transform.xpl:62:37:java.lang.UnsupportedOperationException: There's an error in the table model that cannot be fixed automatically. Go back to the source and correct any errors in the table.
2017-10-10 16:32:23,105 [DEBUG] o.e.persistence.logging.default - Connection(319648319)--Thread(Thread[Thread-16256,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:32:23,106 [ERROR] com.xmlcalabash.runtime.XAtomicStep - bundle://61.0:0/xml/transform/dotify-transform.xpl:62:37:java.lang.UnsupportedOperationException: There's an error in the table model that cannot be fixed automatically. Go back to the source and correct any errors in the table.
2017-10-10 16:32:23,106 [DEBUG] o.e.persistence.logging.default - Connection(231021606)--Thread(Thread[Thread-16256,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:32:23,107 [DEBUG] o.a.h.i.c.PoolingClientConnectionManager - Connection manager is shutting down
2017-10-10 16:32:23,107 [DEBUG] o.a.h.i.c.PoolingClientConnectionManager - Connection manager shut down
2017-10-10 16:32:23,107 [INFO ] org.daisy.pipeline.job.Job - Changing job status to: ERROR
2017-10-10 16:32:23,107 [INFO ] o.d.p.p.impl.job.PersistentJob - Changing Status:ERROR
2017-10-10 16:32:23,107 [DEBUG] o.d.p.p.impl.job.PersistentJob - Updating object
2017-10-10 16:32:23,108 [DEBUG] o.d.p.p.i.job.PersistentJobContext - load script XProcScript[name=DTBook til PEF (NLB)]
2017-10-10 16:32:23,108 [DEBUG] o.d.p.p.i.job.PersistentJobContext - load script XProcScript[name=DTBook til PEF (NLB)]
2017-10-10 16:32:23,108 [DEBUG] o.d.p.p.i.job.PersistentJobContext - Post loading jobcontext
2017-10-10 16:32:23,108 [DEBUG] o.d.p.p.i.job.PersistentJobContext - load script XProcScript[name=DTBook til PEF (NLB)]
2017-10-10 16:32:23,109 [DEBUG] o.e.persistence.logging.default - Connection(1834730855)--Thread(Thread[Thread-16256,5,Configuration Admin Service])--UPDATE jobs SET STATUS = ? WHERE (job_id = ?)
	bind => [2 parameters bound]
2017-10-10 16:32:23,110 [DEBUG] org.daisy.pipeline.push.impl.Poster - Status changed e3a96e14-c9b5-4e57-bca2-1265d4d06331->ERROR
2017-10-10 16:32:23,110 [DEBUG] o.e.persistence.logging.default - Connection(1773272162)--Thread(Thread[Thread-16256,5,Configuration Admin Service])--SELECT job_id, PRIORITY, STATUS, CONTEXT_job_id FROM jobs WHERE (job_id = ?)
	bind => [1 parameter bound]
2017-10-10 16:32:23,111 [DEBUG] o.d.p.p.i.job.PersistentJobContext - load script XProcScript[name=DTBook til PEF (NLB)]
2017-10-10 16:32:23,111 [DEBUG] o.d.p.p.i.job.PersistentJobContext - load script XProcScript[name=DTBook til PEF (NLB)]
2017-10-10 16:32:23,111 [DEBUG] o.d.p.p.i.job.PersistentJobContext - Post loading jobcontext
2017-10-10 16:32:23,112 [DEBUG] o.e.persistence.logging.default - Connection(1372533128)--Thread(Thread[Thread-16256,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:32:23,113 [DEBUG] o.e.persistence.logging.default - Thread(Thread[Thread-16256,5,Configuration Admin Service])--VALUES(1)
2017-10-10 16:32:23,114 [WARN ] o.e.persistence.logging.default - Thread(Thread[Thread-16256,5,Configuration Admin Service])--
2017-10-10 16:32:23,117 [ERROR] org.daisy.pipeline.job.Job - job finished with error state
java.lang.RuntimeException: com.xmlcalabash.core.XProcException: java.lang.UnsupportedOperationException: There's an error in the table model that cannot be fixed automatically. Go back to the source and correct any errors in the table.
	at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:245) ~[na:na]
	at org.daisy.pipeline.job.Job.run(Job.java:216) ~[na:na]
	at org.daisy.pipeline.job.impl.DefaultJobExecutionService$1.run(DefaultJobExecutionService.java:113) ~[na:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Caused by: com.xmlcalabash.core.XProcException: java.lang.UnsupportedOperationException: There's an error in the table model that cannot be fixed automatically. Go back to the source and correct any errors in the table.
	at org.daisy.pipeline.braille.dotify.calabash.impl.OBFLToPEFStep.run(OBFLToPEFStep.java:147) ~[na:na]
	at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:389) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XChoose.run(XChoose.java:135) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at com.xmlcalabash.extensions.Eval.run(Eval.java:249) ~[na:na]
	at org.daisy.pipeline.braille.common.calabash.impl.PxTransformStep.run(PxTransformStep.java:143) ~[na:na]
	at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:389) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XChoose.run(XChoose.java:135) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at com.xmlcalabash.runtime.XPipelineCall.run(XPipelineCall.java:94) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:242) ~[na:na]
	... 3 common frames omitted
Caused by: java.lang.UnsupportedOperationException: There's an error in the table model that cannot be fixed automatically. Go back to the source and correct any errors in the table.
	at org.daisy.dotify.formatter.impl.TableData.completeRow(TableData.java:117) ~[na:na]
	at org.daisy.dotify.formatter.impl.TableData.closeTable(TableData.java:80) ~[na:na]
	at org.daisy.dotify.formatter.impl.Table.closeTable(Table.java:53) ~[na:na]
	at org.daisy.dotify.formatter.impl.FormatterCoreImpl.endTable(FormatterCoreImpl.java:492) ~[na:na]
	at org.daisy.dotify.obfl.ObflParser.parseTable(ObflParser.java:1032) ~[na:na]
	at org.daisy.dotify.obfl.ObflParser.parseSequence(ObflParser.java:573) ~[na:na]
	at org.daisy.dotify.obfl.ObflParser.parse(ObflParser.java:143) ~[na:na]
	at org.daisy.dotify.engine.impl.LayoutEngineImpl.convert(LayoutEngineImpl.java:109) ~[na:na]
	at org.daisy.pipeline.braille.dotify.calabash.impl.OBFLToPEFStep.run(OBFLToPEFStep.java:136) ~[na:na]
	... 20 common frames omitted
2017-10-10 16:32:23,118 [INFO ] o.d.p.j.i.DefaultJobExecutionService - Stopping logging to job's log file
```

See job 1025 on test server.

**Comment by josteinaj** [comment]
This is a `<table>` error, and seems to be caused by the use of the `colspan`and/or `rowspan` attributes.

**Comment by bertfrees** [comment]
The problem is probably that the table is not well-formed and Dotify does not handle this. For example:
```xml
<table>
    <tr>
        <th colspan="3"> </th>
        <td> </td>
        <td rowspan="2"> </td>
    </tr>
    <tr>
        <td> </td>
        <td> </td>
    </tr>
</table>
```

The way to go here I think is to show an error message. Changes are high that malformed complex tables like this one are mistakes, so by automatically inserting empty cells, the risk would be too high that you end up with wrong output without noticing.

I'm not sure how to implement the error message.

- One way would be to improve Dotify's current error message:
   > java.lang.UnsupportedOperationException: There's an error in the table model that cannot be fixed automatically. Go back to the source and correct any errors in the table.

   This could be changed to:
   > file X, line Y, column Z: There's an error in the table model that cannot be fixed automatically. Go back to the source and correct any errors in the table.

   The problem with this is that Dotify currently has no notion of the original source locations of OBFL elements. Some form of source mapping would have to be passed to Dotify in order to support such messages.

- The message could also come from the Pipeline, but that too would require that some source mapping is maintained as the document flows through the conversion.

- A more straightforward solution would be to have a special DTBook/HTML validator step. To check tables can become an option in the dtbook-validator and epub3-validator steps (or in the respective NLB versions).

**Comment by bertfrees** [comment]
I fixed this by adding a validation step (only for DTBook for now).

**Comment by KariRudjord** [comment]
OK
