### ISSUE TITLE
Coding error: unexpected /css:_/book[1]/@css:volume-break-before (mode was table-attr)

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#121]
```
2017-10-10 16:41:44,005 [ERROR] com.xmlcalabash.runtime.XAtomicStep - err:XTRE0540:Ambiguous rule match for /css:_/css:box[1]/@css:page-break-before
Matches both "css:box[@type='block'][not(parent::css:box) and not(preceding-sibling::*)]/@css:page-break-before[.='always']" on line 1392 of bundle://61.0:0/xml/css-to-obfl.xsl
and "css:box[@type='block']/@css:page-break-before[.='always']" on line 1383 of bundle://61.0:0/xml/css-to-obfl.xsl
2017-10-10 16:41:44,006 [DEBUG] o.e.persistence.logging.default - Connection(1889517378)--Thread(Thread[Thread-16259,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:41:44,672 [INFO ] com.xmlcalabash.runtime.XAtomicStep - bundle://61.0:0/xml/css-to-obfl.xpl:574:35:border-left-pattern:⠉ not supported yet
2017-10-10 16:41:44,673 [DEBUG] o.e.persistence.logging.default - Connection(1165790305)--Thread(Thread[Thread-16259,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:41:44,675 [INFO ] com.xmlcalabash.runtime.XAtomicStep - bundle://61.0:0/xml/css-to-obfl.xpl:574:35:border-right-pattern:⠉ not supported yet
2017-10-10 16:41:44,675 [DEBUG] o.e.persistence.logging.default - Connection(1410197174)--Thread(Thread[Thread-16259,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:41:44,679 [INFO ] com.xmlcalabash.runtime.XAtomicStep - bundle://61.0:0/xml/css-to-obfl.xpl:574:35:border-left-pattern:⠉ not supported yet
2017-10-10 16:41:44,680 [DEBUG] o.e.persistence.logging.default - Connection(1608620441)--Thread(Thread[Thread-16259,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:41:44,682 [INFO ] com.xmlcalabash.runtime.XAtomicStep - bundle://61.0:0/xml/css-to-obfl.xpl:574:35:border-right-pattern:⠉ not supported yet
2017-10-10 16:41:44,682 [DEBUG] o.e.persistence.logging.default - Connection(1236643087)--Thread(Thread[Thread-16259,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:41:45,215 [INFO ] com.xmlcalabash.runtime.XAtomicStep - bundle://61.0:0/xml/css-to-obfl.xpl:574:35:Coding error: unexpected /css:_/book[1]/@css:volume-break-before (mode was table-attr)
2017-10-10 16:41:45,216 [DEBUG] o.e.persistence.logging.default - Connection(944329218)--Thread(Thread[Thread-16259,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:41:45,218 [ERROR] com.xmlcalabash.runtime.XAtomicStep - bundle://61.0:0/xml/css-to-obfl.xsl:2112:XTMM9000:Processing terminated by xsl:message at line 2112 in css-to-obfl.xsl
2017-10-10 16:41:45,218 [DEBUG] o.e.persistence.logging.default - Connection(415769392)--Thread(Thread[Thread-16259,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:41:45,219 [ERROR] com.xmlcalabash.runtime.XAtomicStep - Processing terminated by xsl:message at line 2112 in css-to-obfl.xsl
2017-10-10 16:41:45,220 [DEBUG] o.e.persistence.logging.default - Connection(1981326093)--Thread(Thread[Thread-16259,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:41:45,220 [ERROR] com.xmlcalabash.runtime.XAtomicStep - Processing terminated by xsl:message at line 2112 in css-to-obfl.xsl
2017-10-10 16:41:45,220 [DEBUG] o.e.persistence.logging.default - Connection(1169451992)--Thread(Thread[Thread-16259,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:41:45,221 [DEBUG] o.a.h.i.c.PoolingClientConnectionManager - Connection manager is shutting down
2017-10-10 16:41:45,221 [DEBUG] o.a.h.i.c.PoolingClientConnectionManager - Connection manager shut down
2017-10-10 16:41:45,221 [ERROR] com.xmlcalabash.runtime.XAtomicStep - Processing terminated by xsl:message at line 2112 in css-to-obfl.xsl
2017-10-10 16:41:45,222 [DEBUG] o.e.persistence.logging.default - Connection(156943694)--Thread(Thread[Thread-16259,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:41:45,222 [ERROR] com.xmlcalabash.runtime.XAtomicStep - Processing terminated by xsl:message at line 2112 in css-to-obfl.xsl
2017-10-10 16:41:45,222 [DEBUG] o.e.persistence.logging.default - Connection(1291678351)--Thread(Thread[Thread-16259,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:41:45,223 [DEBUG] o.a.h.i.c.PoolingClientConnectionManager - Connection manager is shutting down
2017-10-10 16:41:45,223 [DEBUG] o.a.h.i.c.PoolingClientConnectionManager - Connection manager shut down
2017-10-10 16:41:45,223 [INFO ] org.daisy.pipeline.job.Job - Changing job status to: ERROR
2017-10-10 16:41:45,223 [INFO ] o.d.p.p.impl.job.PersistentJob - Changing Status:ERROR
2017-10-10 16:41:45,223 [DEBUG] o.d.p.p.impl.job.PersistentJob - Updating object
2017-10-10 16:41:45,223 [DEBUG] o.d.p.p.i.job.PersistentJobContext - load script XProcScript[name=DTBook til PEF (NLB)]
2017-10-10 16:41:45,224 [DEBUG] o.d.p.p.i.job.PersistentJobContext - load script XProcScript[name=DTBook til PEF (NLB)]
2017-10-10 16:41:45,224 [DEBUG] o.d.p.p.i.job.PersistentJobContext - Post loading jobcontext
2017-10-10 16:41:45,224 [DEBUG] o.d.p.p.i.job.PersistentJobContext - load script XProcScript[name=DTBook til PEF (NLB)]
2017-10-10 16:41:45,225 [DEBUG] o.e.persistence.logging.default - Connection(957884989)--Thread(Thread[Thread-16259,5,Configuration Admin Service])--UPDATE jobs SET STATUS = ? WHERE (job_id = ?)
	bind => [2 parameters bound]
2017-10-10 16:41:45,226 [DEBUG] org.daisy.pipeline.push.impl.Poster - Status changed 8e9648c6-1b91-4ca1-b9c5-ff5f1b16169f->ERROR
2017-10-10 16:41:45,226 [DEBUG] o.e.persistence.logging.default - Connection(755422052)--Thread(Thread[Thread-16259,5,Configuration Admin Service])--SELECT job_id, PRIORITY, STATUS, CONTEXT_job_id FROM jobs WHERE (job_id = ?)
	bind => [1 parameter bound]
2017-10-10 16:41:45,227 [DEBUG] o.d.p.p.i.job.PersistentJobContext - load script XProcScript[name=DTBook til PEF (NLB)]
2017-10-10 16:41:45,227 [DEBUG] o.d.p.p.i.job.PersistentJobContext - load script XProcScript[name=DTBook til PEF (NLB)]
2017-10-10 16:41:45,227 [DEBUG] o.d.p.p.i.job.PersistentJobContext - Post loading jobcontext
2017-10-10 16:41:45,227 [DEBUG] o.e.persistence.logging.default - Connection(1401112196)--Thread(Thread[Thread-16259,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-10 16:41:45,229 [DEBUG] o.e.persistence.logging.default - Thread(Thread[Thread-16259,5,Configuration Admin Service])--VALUES(1)
2017-10-10 16:41:45,229 [WARN ] o.e.persistence.logging.default - Thread(Thread[Thread-16259,5,Configuration Admin Service])--
2017-10-10 16:41:45,233 [ERROR] org.daisy.pipeline.job.Job - job finished with error state
java.lang.RuntimeException: net.sf.saxon.s9api.SaxonApiException: Processing terminated by xsl:message at line 2112 in css-to-obfl.xsl
	at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:245) ~[na:na]
	at org.daisy.pipeline.job.Job.run(Job.java:216) ~[na:na]
	at org.daisy.pipeline.job.impl.DefaultJobExecutionService$1.run(DefaultJobExecutionService.java:113) ~[na:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Caused by: net.sf.saxon.s9api.SaxonApiException: Processing terminated by xsl:message at line 2112 in css-to-obfl.xsl
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:453) ~[na:na]
	at com.xmlcalabash.library.XSLT.run(XSLT.java:251) ~[na:na]
	at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:389) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at com.xmlcalabash.runtime.XPipelineCall.run(XPipelineCall.java:94) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at com.xmlcalabash.extensions.Eval.run(Eval.java:249) ~[na:na]
	at org.daisy.pipeline.braille.common.calabash.impl.PxTransformStep.run(PxTransformStep.java:143) ~[na:na]
	at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:389) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XChoose.run(XChoose.java:135) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at com.xmlcalabash.runtime.XPipelineCall.run(XPipelineCall.java:94) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:242) ~[na:na]
	... 3 common frames omitted
Caused by: net.sf.saxon.expr.instruct.TerminationException: Processing terminated by xsl:message at line 2112 in css-to-obfl.xsl
	at net.sf.saxon.expr.instruct.Message.processLeavingTail(Message.java:274) ~[na:na]
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:660) ~[na:na]
	at net.sf.saxon.expr.instruct.Template.expand(Template.java:258) ~[na:na]
	at net.sf.saxon.expr.instruct.CallTemplate$CallTemplatePackage.processLeavingTail(CallTemplate.java:536) ~[na:na]
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:1028) ~[na:na]
	at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:281) ~[na:na]
	at net.sf.saxon.expr.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:241) ~[na:na]
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:660) ~[na:na]
	at net.sf.saxon.expr.instruct.Template.applyLeavingTail(Template.java:239) ~[na:na]
	at net.sf.saxon.expr.instruct.NextMatch$NextMatchPackage.processLeavingTail(NextMatch.java:196) ~[na:na]
	at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:283) ~[na:na]
	at net.sf.saxon.expr.instruct.ApplyTemplates.process(ApplyTemplates.java:237) ~[na:na]
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:431) ~[na:na]
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:373) ~[na:na]
	at net.sf.saxon.expr.instruct.Template.applyLeavingTail(Template.java:239) ~[na:na]
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:1057) ~[na:na]
	at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:281) ~[na:na]
	at net.sf.saxon.expr.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:241) ~[na:na]
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:660) ~[na:na]
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:138) ~[na:na]
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:431) ~[na:na]
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:373) ~[na:na]
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:138) ~[na:na]
	at net.sf.saxon.expr.instruct.ForEachGroup.processLeavingTail(ForEachGroup.java:747) ~[na:na]
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:138) ~[na:na]
	at net.sf.saxon.expr.instruct.ForEachGroup.processLeavingTail(ForEachGroup.java:747) ~[na:na]
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:138) ~[na:na]
	at net.sf.saxon.expr.instruct.ForEachGroup.processLeavingTail(ForEachGroup.java:747) ~[na:na]
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:138) ~[na:na]
	at net.sf.saxon.expr.LetExpression.process(LetExpression.java:463) ~[na:na]
	at net.sf.saxon.expr.instruct.ForEachGroup.processLeavingTail(ForEachGroup.java:747) ~[na:na]
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:138) ~[na:na]
	at net.sf.saxon.expr.LetExpression.process(LetExpression.java:463) ~[na:na]
	at net.sf.saxon.expr.instruct.ForEachGroup.processLeavingTail(ForEachGroup.java:747) ~[na:na]
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:660) ~[na:na]
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:613) ~[na:na]
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:660) ~[na:na]
	at net.sf.saxon.expr.instruct.Template.expand(Template.java:258) ~[na:na]
	at net.sf.saxon.expr.instruct.CallTemplate.process(CallTemplate.java:347) ~[na:na]
	at net.sf.saxon.expr.instruct.CallTemplate.processLeavingTail(CallTemplate.java:395) ~[na:na]
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:660) ~[na:na]
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:613) ~[na:na]
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:660) ~[na:na]
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:138) ~[na:na]
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:431) ~[na:na]
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:373) ~[na:na]
	at net.sf.saxon.expr.instruct.Template.expand(Template.java:258) ~[na:na]
	at net.sf.saxon.Controller.transformDocument(Controller.java:2092) ~[na:na]
	at net.sf.saxon.Controller.transform(Controller.java:1903) ~[na:na]
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:450) ~[na:na]
	... 22 common frames omitted
2017-10-10 16:41:45,234 [INFO ] o.d.p.j.i.DefaultJobExecutionService - Stopping logging to job's log file
```

TODO: create test case

See job 1027 on test server.

**Comment by josteinaj** [comment]
This issue seems to be related to tables and volume breaking.

**Comment by bertfrees** [comment]
Fixed

**Comment by KariRudjord** [comment]
I tried the book over again, (561687). It still failes.

**Comment by bertfrees** [comment]
Still the same error? Was it job 1218?

**Comment by KariRudjord** [comment]
Job 1218, yes. Failed to complete volume division.

**Comment by bertfrees** [comment]
OK, it's a different error then.

**Comment by josteinaj** [comment]
@KariRudjord I'm moving this back to "Ready for testing" since it turned out to be a different error. The "Failed to complete volume division" error is most likely this issue: #118 

Do you remember if you previously got the error "`Coding error: unexpected /css:_/book[1]/@css:volume-break-before (mode was table-attr)`" for 561687? If so, you can move it to "Done". If you don't remember, let's just leave this on "Ready for testing" for a week and see if this error occurs again. If you haven't encountered this error within a week we can say that it's fixed.

**Comment by KariRudjord** [comment]
OK
