### ISSUE TITLE
dotify:obfl-to-pef failed: Failed to solve table

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#129]
```
2017-10-17 17:24:20,449 [ERROR] o.d.p.b.d.c.impl.OBFLToPEFStep - dotify:obfl-to-pef failed
java.lang.RuntimeException: java.lang.RuntimeException: Failed to solve table.
	at org.daisy.dotify.formatter.impl.ScenarioProcessor.invalidateScenario(ScenarioProcessor.java:156) ~[na:na]
	at org.daisy.dotify.formatter.impl.ScenarioProcessor.process(ScenarioProcessor.java:59) ~[na:na]
	at org.daisy.dotify.formatter.impl.RowGroupBuilder.getResult(RowGroupBuilder.java:24) ~[na:na]
	at org.daisy.dotify.formatter.impl.PageSequenceBuilder2.<init>(PageSequenceBuilder2.java:70) ~[na:na]
	at org.daisy.dotify.formatter.impl.SheetDataSource.ensureBuffer(SheetDataSource.java:116) ~[na:na]
	at org.daisy.dotify.formatter.impl.SheetDataSource.getRemaining(SheetDataSource.java:59) ~[na:na]
	at org.daisy.dotify.formatter.impl.VolumeProvider.prepare(VolumeProvider.java:87) ~[na:na]
	at org.daisy.dotify.formatter.impl.FormatterImpl.getVolumes(FormatterImpl.java:138) ~[na:na]
	at org.daisy.dotify.formatter.impl.FormatterImpl.write(FormatterImpl.java:123) ~[na:na]
	at org.daisy.dotify.engine.impl.LayoutEngineImpl.convert(LayoutEngineImpl.java:128) ~[na:na]
	at org.daisy.pipeline.braille.dotify.calabash.impl.OBFLToPEFStep.run(OBFLToPEFStep.java:136) ~[na:na]
	at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:389) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XChoose.run(XChoose.java:135) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at com.xmlcalabash.extensions.Eval.run(Eval.java:249) ~[na:na]
	at org.daisy.pipeline.braille.common.calabash.impl.PxTransformStep.run(PxTransformStep.java:143) ~[na:na]
	at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:389) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XChoose.run(XChoose.java:135) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at com.xmlcalabash.runtime.XPipelineCall.run(XPipelineCall.java:94) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:242) ~[na:na]
	at org.daisy.pipeline.job.Job.run(Job.java:216) ~[na:na]
	at org.daisy.pipeline.job.impl.DefaultJobExecutionService$1.run(DefaultJobExecutionService.java:113) ~[na:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Caused by: java.lang.RuntimeException: Failed to solve table.
	at org.daisy.dotify.formatter.impl.Table.minimizeCost(Table.java:136) ~[na:na]
	at org.daisy.dotify.formatter.impl.Table.newBlockContentManager(Table.java:90) ~[na:na]
	at org.daisy.dotify.formatter.impl.Block.getBlockContentManager(Block.java:151) ~[na:na]
	at org.daisy.dotify.formatter.impl.ScenarioProcessor.processBlockInner(ScenarioProcessor.java:77) ~[na:na]
	at org.daisy.dotify.formatter.impl.ScenarioProcessor.processBlock(ScenarioProcessor.java:72) ~[na:na]
	at org.daisy.dotify.formatter.impl.ScenarioProcessor.process(ScenarioProcessor.java:57) ~[na:na]
	... 29 common frames omitted
2017-10-17 17:24:20,450 [ERROR] com.xmlcalabash.runtime.XAtomicStep - bundle://61.0:0/xml/transform/dotify-transform.xpl:62:37:java.lang.RuntimeException: java.lang.RuntimeException: Failed to solve table.
2017-10-17 17:24:20,451 [DEBUG] o.e.persistence.logging.default - Connection(1197763791)--Thread(Thread[Thread-117,5,main])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-17 17:24:20,467 [DEBUG] o.a.h.i.c.PoolingClientConnectionManager - Connection manager is shutting down
2017-10-17 17:24:20,467 [DEBUG] o.a.h.i.c.PoolingClientConnectionManager - Connection manager shut down
2017-10-17 17:24:20,467 [ERROR] com.xmlcalabash.runtime.XAtomicStep - bundle://61.0:0/xml/transform/dotify-transform.xpl:62:37:java.lang.RuntimeException: java.lang.RuntimeException: Failed to solve table.
2017-10-17 17:24:20,467 [DEBUG] o.e.persistence.logging.default - Connection(777014792)--Thread(Thread[Thread-117,5,main])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-17 17:24:20,468 [ERROR] com.xmlcalabash.runtime.XAtomicStep - bundle://61.0:0/xml/transform/dotify-transform.xpl:62:37:java.lang.RuntimeException: java.lang.RuntimeException: Failed to solve table.
2017-10-17 17:24:20,469 [DEBUG] o.e.persistence.logging.default - Connection(2095849229)--Thread(Thread[Thread-117,5,main])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-17 17:24:20,469 [DEBUG] o.a.h.i.c.PoolingClientConnectionManager - Connection manager is shutting down
2017-10-17 17:24:20,469 [DEBUG] o.a.h.i.c.PoolingClientConnectionManager - Connection manager shut down
2017-10-17 17:24:20,469 [INFO ] org.daisy.pipeline.job.Job - Changing job status to: ERROR
2017-10-17 17:24:20,469 [INFO ] o.d.p.p.impl.job.PersistentJob - Changing Status:ERROR
2017-10-17 17:24:20,469 [DEBUG] o.d.p.p.impl.job.PersistentJob - Updating object
2017-10-17 17:24:20,470 [DEBUG] o.d.p.p.i.job.PersistentJobContext - load script XProcScript[name=DTBook til PEF (NLB)]
2017-10-17 17:24:20,470 [DEBUG] o.d.p.p.i.job.PersistentJobContext - load script XProcScript[name=DTBook til PEF (NLB)]
2017-10-17 17:24:20,470 [DEBUG] o.d.p.p.i.job.PersistentJobContext - Post loading jobcontext
2017-10-17 17:24:20,470 [DEBUG] o.d.p.p.i.job.PersistentJobContext - load script XProcScript[name=DTBook til PEF (NLB)]
2017-10-17 17:24:20,472 [DEBUG] o.e.persistence.logging.default - Connection(110206618)--Thread(Thread[Thread-117,5,main])--UPDATE jobs SET STATUS = ? WHERE (job_id = ?)
	bind => [2 parameters bound]
2017-10-17 17:24:20,473 [DEBUG] org.daisy.pipeline.push.impl.Poster - Status changed 27a4430d-5bd8-4a63-9d04-b347b1938d8a->ERROR
2017-10-17 17:24:20,473 [DEBUG] o.e.persistence.logging.default - Connection(1415403027)--Thread(Thread[Thread-117,5,main])--SELECT job_id, PRIORITY, STATUS, CONTEXT_job_id FROM jobs WHERE (job_id = ?)
	bind => [1 parameter bound]
2017-10-17 17:24:20,474 [DEBUG] o.d.p.p.i.job.PersistentJobContext - load script XProcScript[name=DTBook til PEF (NLB)]
2017-10-17 17:24:20,474 [DEBUG] o.d.p.p.i.job.PersistentJobContext - load script XProcScript[name=DTBook til PEF (NLB)]
2017-10-17 17:24:20,474 [DEBUG] o.d.p.p.i.job.PersistentJobContext - Post loading jobcontext
2017-10-17 17:24:20,474 [DEBUG] o.e.persistence.logging.default - Connection(1504362469)--Thread(Thread[Thread-117,5,main])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-10-17 17:24:20,476 [DEBUG] o.e.persistence.logging.default - Thread(Thread[Thread-117,5,main])--VALUES(1)
2017-10-17 17:24:20,476 [WARN ] o.e.persistence.logging.default - Thread(Thread[Thread-117,5,main])--
2017-10-17 17:24:20,481 [ERROR] org.daisy.pipeline.job.Job - job finished with error state
java.lang.RuntimeException: com.xmlcalabash.core.XProcException: java.lang.RuntimeException: java.lang.RuntimeException: Failed to solve table.
	at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:245) ~[na:na]
	at org.daisy.pipeline.job.Job.run(Job.java:216) ~[na:na]
	at org.daisy.pipeline.job.impl.DefaultJobExecutionService$1.run(DefaultJobExecutionService.java:113) ~[na:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Caused by: com.xmlcalabash.core.XProcException: java.lang.RuntimeException: java.lang.RuntimeException: Failed to solve table.
	at org.daisy.pipeline.braille.dotify.calabash.impl.OBFLToPEFStep.run(OBFLToPEFStep.java:147) ~[na:na]
	at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:389) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XChoose.run(XChoose.java:135) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at com.xmlcalabash.extensions.Eval.run(Eval.java:249) ~[na:na]
	at org.daisy.pipeline.braille.common.calabash.impl.PxTransformStep.run(PxTransformStep.java:143) ~[na:na]
	at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:389) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XChoose.run(XChoose.java:135) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at com.xmlcalabash.runtime.XPipelineCall.run(XPipelineCall.java:94) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:242) ~[na:na]
	... 3 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to solve table.
	at org.daisy.dotify.formatter.impl.ScenarioProcessor.invalidateScenario(ScenarioProcessor.java:156) ~[na:na]
	at org.daisy.dotify.formatter.impl.ScenarioProcessor.process(ScenarioProcessor.java:59) ~[na:na]
	at org.daisy.dotify.formatter.impl.RowGroupBuilder.getResult(RowGroupBuilder.java:24) ~[na:na]
	at org.daisy.dotify.formatter.impl.PageSequenceBuilder2.<init>(PageSequenceBuilder2.java:70) ~[na:na]
	at org.daisy.dotify.formatter.impl.SheetDataSource.ensureBuffer(SheetDataSource.java:116) ~[na:na]
	at org.daisy.dotify.formatter.impl.SheetDataSource.getRemaining(SheetDataSource.java:59) ~[na:na]
	at org.daisy.dotify.formatter.impl.VolumeProvider.prepare(VolumeProvider.java:87) ~[na:na]
	at org.daisy.dotify.formatter.impl.FormatterImpl.getVolumes(FormatterImpl.java:138) ~[na:na]
	at org.daisy.dotify.formatter.impl.FormatterImpl.write(FormatterImpl.java:123) ~[na:na]
	at org.daisy.dotify.engine.impl.LayoutEngineImpl.convert(LayoutEngineImpl.java:128) ~[na:na]
	at org.daisy.pipeline.braille.dotify.calabash.impl.OBFLToPEFStep.run(OBFLToPEFStep.java:136) ~[na:na]
	... 20 common frames omitted
Caused by: java.lang.RuntimeException: Failed to solve table.
	at org.daisy.dotify.formatter.impl.Table.minimizeCost(Table.java:136) ~[na:na]
	at org.daisy.dotify.formatter.impl.Table.newBlockContentManager(Table.java:90) ~[na:na]
	at org.daisy.dotify.formatter.impl.Block.getBlockContentManager(Block.java:151) ~[na:na]
	at org.daisy.dotify.formatter.impl.ScenarioProcessor.processBlockInner(ScenarioProcessor.java:77) ~[na:na]
	at org.daisy.dotify.formatter.impl.ScenarioProcessor.processBlock(ScenarioProcessor.java:72) ~[na:na]
	at org.daisy.dotify.formatter.impl.ScenarioProcessor.process(ScenarioProcessor.java:57) ~[na:na]
	... 29 common frames omitted
2017-10-17 17:24:20,482 [INFO ] o.d.p.j.i.DefaultJobExecutionService - Stopping logging to job's log file
```

**Comment by josteinaj** [comment]
Test here: d7f4fcbf69ff67464d480ac486d8fac1093062ab

**Comment by bertfrees** [comment]
See also https://github.com/brailleapps/dotify.formatter.impl/issues/27.

**Comment by bertfrees** [comment]
The table in the test is simply too big. It has 10 columns and you want to fit them into a 29 cell wide page. I have improved the error message a bit.

**Comment by josteinaj** [comment]
@KariRudjord could you check what the error message is now and if it's clear from the message why it failed and what table it failed on? You can also make a separate issue for handling big tables if you want.

**Comment by KariRudjord** [comment]
I can't remember what I tested with, but I do as you suggest and make a separate issue for handling big tables (If its not already made a card, I check) @josteinaj
