### ISSUE TITLE
PaginatorException: Row is too long (33/32)

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#147]
I was looking at #114 and so I tried converting our largest book. The DTBook is 8.7MB. It took a really long time to run, maybe 30-40 minutes, and then the job status returned was VALIDATION_FAIL. In the log I found the following exception:

```
2017-11-23 15:25:25,943 [ERROR] o.d.p.b.d.c.impl.OBFLToPEFStep - dotify:obfl-to-pef failed
org.daisy.dotify.formatter.impl.core.PaginatorException: Row is too long (33/32) '⠀⠀⠀⠀⠀⠀⠠⠁⠇⠙⠑⠗⠑⠝⠀⠀⠼⠚⠤⠀⠀⠼⠋⠀⠀⠼⠁⠁⠀⠀⠼⠁⠑'
	at org.daisy.dotify.formatter.impl.core.BorderManager.addBorders(BorderManager.java:220) ~[na:na]
	at org.daisy.dotify.formatter.impl.core.BorderManager.addRow(BorderManager.java:110) ~[na:na]
	at org.daisy.dotify.formatter.impl.page.PageImpl.newRow(PageImpl.java:110) ~[na:na]
	at org.daisy.dotify.formatter.impl.page.PageSequenceBuilder2.addRows(PageSequenceBuilder2.java:280) ~[na:na]
	at org.daisy.dotify.formatter.impl.page.PageSequenceBuilder2.nextPageInner(PageSequenceBuilder2.java:230) ~[na:na]
	at org.daisy.dotify.formatter.impl.page.PageSequenceBuilder2.nextPage(PageSequenceBuilder2.java:155) ~[na:na]
	at org.daisy.dotify.formatter.impl.sheet.SheetDataSource.ensureBuffer(SheetDataSource.java:214) ~[na:na]
	at org.daisy.dotify.formatter.impl.sheet.SheetDataSource.getRemaining(SheetDataSource.java:114) ~[na:na]
	at org.daisy.dotify.formatter.impl.VolumeProvider.prepare(VolumeProvider.java:104) ~[na:na]
	at org.daisy.dotify.formatter.impl.FormatterImpl.getVolumes(FormatterImpl.java:139) ~[na:na]
	at org.daisy.dotify.formatter.impl.FormatterImpl.write(FormatterImpl.java:123) ~[na:na]
	at org.daisy.dotify.engine.impl.LayoutEngineImpl.convert(LayoutEngineImpl.java:128) ~[na:na]
	at org.daisy.pipeline.braille.dotify.calabash.impl.OBFLToPEFStep.run(OBFLToPEFStep.java:136) ~[na:na]
	at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:389) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XChoose.run(XChoose.java:135) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at com.xmlcalabash.extensions.Eval.run(Eval.java:249) ~[na:na]
	at org.daisy.pipeline.braille.common.calabash.impl.PxTransformStep.run(PxTransformStep.java:143) ~[na:na]
	at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:389) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XChoose.run(XChoose.java:135) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at com.xmlcalabash.runtime.XPipelineCall.run(XPipelineCall.java:94) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XTry.run(XTry.java:98) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:242) ~[na:na]
	at org.daisy.pipeline.job.Job.run(Job.java:216) ~[na:na]
	at org.daisy.pipeline.job.impl.DefaultJobExecutionService$1.run(DefaultJobExecutionService.java:113) ~[na:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
2017-11-23 15:25:25,944 [ERROR] com.xmlcalabash.runtime.XAtomicStep - bundle://174.0:0/xml/transform/dotify-transform.xpl:62:37:org.daisy.dotify.formatter.impl.core.PaginatorException: Row is too long (33/32) '⠀⠀⠀⠀⠀⠀⠠⠁⠇⠙⠑⠗⠑⠝⠀⠀⠼⠚⠤⠀⠀⠼⠋⠀⠀⠼⠁⠁⠀⠀⠼⠁⠑'
2017-11-23 15:25:25,944 [DEBUG] o.e.persistence.logging.default - Connection(651397218)--Thread(Thread[Thread-69,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-11-23 15:25:25,946 [DEBUG] o.a.h.i.c.PoolingClientConnectionManager - Connection manager is shutting down
2017-11-23 15:25:25,946 [DEBUG] o.a.h.i.c.PoolingClientConnectionManager - Connection manager shut down
2017-11-23 15:25:25,946 [ERROR] com.xmlcalabash.runtime.XAtomicStep - bundle://174.0:0/xml/transform/dotify-transform.xpl:62:37:org.daisy.dotify.formatter.impl.core.PaginatorException: Row is too long (33/32) '⠀⠀⠀⠀⠀⠀⠠⠁⠇⠙⠑⠗⠑⠝⠀⠀⠼⠚⠤⠀⠀⠼⠋⠀⠀⠼⠁⠁⠀⠀⠼⠁⠑'
2017-11-23 15:25:25,947 [DEBUG] o.e.persistence.logging.default - Connection(1088118898)--Thread(Thread[Thread-69,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
```

I don't think there's a copyright on this book (it's the official collection of norwegian laws). However, I've obfuscated it before uploading it here:
[560616-biggest-book.xml.txt](https://github.com/nlbdev/pipeline/files/1499556/560616-biggest-book.xml.txt)

I can send the original on Slack if necessary.

**Comment by bertfrees** [comment]
Does it still fail when obfuscated? I don't want to wait 40 minutes to run the whole book again in order to find out.

Could you check if the book still fails if you make it much smaller but keep the part with the offending text? It back-translates to "Alderen  0-  6  11  15".

**Comment by josteinaj** [comment]
Didn't try obfuscated. I found the place you referenced. It's a table, and I can reduce it to this and still get the error:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dtbook
  PUBLIC "-//NISO//DTD dtbook 2005-3//EN" "http://www.daisy.org/z3986/2005/dtbook-2005-3.dtd">
<dtbook xmlns="http://www.daisy.org/z3986/2005/dtbook/" xml:lang="no" version="2005-3">
    <head>
        <meta name="dc:Title" content="Norges lover : 2016-2017"/> 
        <meta name="dc:Identifier" content="560616"/> 
        <meta name="dc:Language" content="no"/> 
        <meta name="dc:Publisher" content="NLB"/> 
    </head>
    <book>
        <frontmatter> 
            <doctitle>Norges lover : 2016-2017</doctitle>
        </frontmatter>
        <bodymatter>
            <level1 id="level1_17" class="part"> 
                <h1 id="h1_16">1981 6 mars. Nr. 5. 1981 Lov om barneombud [barneombudsloven].</h1> 
                <level2 id="level2_115" class="chapter"> 
                    <level3 id="level3_481"> 
                        <sidebar id="sidebar_4" render="optional">
                            <table>
                                <caption><em>Forbruksutgifter og buutgifter</em></caption>
                                <tr>
                                    <td>Alderen til barnet</td>
                                    <td>0–5 år</td>
                                    <td>6–10 år</td>
                                </tr>
                            </table>
                        </sidebar>
                    </level3> 
                </level2>
            </level1>
        </bodymatter>
    </book>
</dtbook>
```

The full table looks like this:

```xml
<table>
    <caption><em>Forbruksutgifter og buutgifter</em></caption>
    <tr>
        <th>Alderen til barnet</th>
        <th>0–5 år</th>
        <th>6–10 år</th>
        <th>11–14 år</th>
        <th>15 år og meir</th>
    </tr>
    <tr>
        <td>Forbruksutgifter</td>
        <td>3 489</td>
        <td>4 869</td>
        <td>5 794</td>
        <td>6 644</td>
    </tr>
    <pagenum id="page-123" page="normal">123</pagenum>
    <tr>
        <td>Buutgifter</td>
        <td>2 577</td>
        <td>2 577</td>
        <td>2 577</td>
        <td>2 577</td>
    </tr>
</table>
```

**Comment by bertfrees** [comment]
Thanks!

It looks like a Dotify bug with tables. The "Alderen 0- 6 11 15" looks like the first row of the table header in which every cell is wrapped over several rows.

You'll probably don't want to layout such tables in matrix form. In this sense it is related to https://github.com/nlbdev/pipeline/issues/145. But still, Dotify should be able to handle this example.

**Comment by bertfrees** [comment]
See https://github.com/brailleapps/dotify.formatter.impl/pull/35. It looks like it has nothing to do with big tables, but with the left padding. Maybe you can try a left margin instead because there is no border anyway?

**Comment by bertfrees** [comment]
Hold on, actually I don't see any left padding in the CSS. Let me check where it came from...

**Comment by bertfrees** [comment]
OK the `padding-left: 2` is coming from the `margin-left: 2` on the `sidebar`. So you can't work around it with CSS.

**Comment by bertfrees** [comment]
Fixed.

**Comment by josteinaj** [comment]
@KariRudjord have you seen the error "PaginatorException: Row is too long (33/32)" lately? If not, I think we'll say that this one is done.

**Comment by KariRudjord** [comment]
No, I haven't, so I'm closing this.
