### ISSUE TITLE
Production fails when xml:lang="en" and force-norwegian="false" (ArrayIndexOutOfBoundsException)

### ISSUE THREAD

**Issue by matskober** [nlbdev/pipeline#155]
See job#1820 and job#1821. 

Same EPUB, Harry Potter, in English. If uncheking "alltid norsk" the production failes, but succedes if the box is checked.

**Comment by josteinaj** [comment]
Reproduced:

```
2017-12-14 15:14:52,354 [DEBUG] o.d.c.x.c.steps.Message$MessageStep - bundle://84.0:1/xml/xproc/message.xpl:116:29:px:transform query=(input:css)(output:pef)(formatter:dotify)(translator:nlb)(dots:6)(grade:0)(locale:en)
2017-12-14 15:14:52,354 [DEBUG] com.xmlcalabash.library.DefaultStep - Running {http://www.daisy.org/ns/pipeline/xproc}log-message !1.23.2.1
2017-12-14 15:14:52,354 [DEBUG] com.xmlcalabash.library.Identity - Running identity result
2017-12-14 15:14:52,355 [INFO ] com.xmlcalabash - Selected o.d.p.b.dotify.impl.DotifyCSSStyledDocumentTransform$Provider$TransformImpl{output=pef, blockTransform=NLBTranslator{grade=0, dots=6}, id=transform5} for query (input:css)(output:pef)(formatter:dotify)(translator:nlb)(dots:6)(grade:0)(locale:en)
2017-12-14 15:14:52,355 [DEBUG] o.e.persistence.logging.default - Connection(375815171)--Thread(Thread[Thread-1862,5,main])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-12-14 15:14:52,356 [DEBUG] com.xmlcalabash.library.DefaultStep - Running {http://www.daisy.org/ns/pipeline/xproc}transform !1.45.3.4.3
2017-12-14 15:14:52,450 [DEBUG] com.xmlcalabash.library.Identity - Running identity !1.14.1
2017-12-14 15:14:52,451 [INFO ] com.xmlcalabash - Selected NLBTranslator{grade=0, dots=6} for query (translator:nlb)(dots:6)(grade:0)(locale:en)(input:css)(output:css)
2017-12-14 15:14:52,452 [DEBUG] o.e.persistence.logging.default - Connection(306958242)--Thread(Thread[Thread-1862,5,main])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-12-14 15:14:52,453 [DEBUG] com.xmlcalabash.library.DefaultStep - Running {http://www.daisy.org/ns/pipeline/xproc}transform !1.15
2017-12-14 15:14:52,510 [DEBUG] com.xmlcalabash.library.XSLT - Running xslt !1.5
2017-12-14 15:14:54,675 [DEBUG] com.xmlcalabash.library.XSLT - Running xslt !1.5
2017-12-14 15:14:54,718 [ERROR] com.xmlcalabash - err:SXXP0005:The source document is in namespace http://www.w3.org/1999/xhtml, but none of the template rules match elements in this namespace
2017-12-14 15:14:54,719 [DEBUG] o.e.persistence.logging.default - Connection(1334587074)--Thread(Thread[Thread-1862,5,main])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2017-12-14 15:15:10,111 [ERROR] o.d.p.b.c.s.i.TextTransformDefinition - pf:text-transform failed
java.lang.ArrayIndexOutOfBoundsException: 228
	at org.liblouis.TranslationResult.<init>(TranslationResult.java:31) ~[na:na]
	at org.liblouis.Translator.translate(Translator.java:95) ~[na:na]
	at org.daisy.pipeline.braille.liblouis.impl.LiblouisTranslatorJnaImplProvider$LiblouisTranslatorImpl.transform(LiblouisTranslatorJnaImplProvider.java:1238) ~[na:na]
	at org.daisy.pipeline.braille.liblouis.impl.LiblouisTranslatorJnaImplProvider$LiblouisTranslatorImpl.transform(LiblouisTranslatorJnaImplProvider.java:1045) ~[na:na]
	at org.daisy.pipeline.braille.liblouis.impl.LiblouisTranslatorJnaImplProvider$LiblouisTranslatorImpl.transform(LiblouisTranslatorJnaImplProvider.java:977) ~[na:na]
	at org.daisy.pipeline.braille.liblouis.impl.LiblouisTranslatorJnaImplProvider$LiblouisTranslatorImpl.access$600(LiblouisTranslatorJnaImplProvider.java:292) ~[na:na]
	at org.daisy.pipeline.braille.liblouis.impl.LiblouisTranslatorJnaImplProvider$LiblouisTranslatorImpl$2.transform(LiblouisTranslatorJnaImplProvider.java:358) ~[na:na]
	at no.nlb.pipeline.braille.impl.NLBTranslator$Provider$TransformImpl.transformWithContractionGrade(NLBTranslator.java:395) ~[na:na]
	at no.nlb.pipeline.braille.impl.NLBTranslator$Provider$TransformImpl.access$600(NLBTranslator.java:214) ~[na:na]
	at no.nlb.pipeline.braille.impl.NLBTranslator$Provider$TransformImpl$1.transform(NLBTranslator.java:375) ~[na:na]
	at no.nlb.pipeline.braille.impl.NLBTranslator$Provider$TransformImpl$1.transform(NLBTranslator.java:280) ~[na:na]
	at no.nlb.pipeline.braille.impl.NLBTranslator$Provider$TransformImpl$1.transform(NLBTranslator.java:271) ~[na:na]
```
