### ISSUE TITLE
ArrayIndexOutOfBoundsException in LiblouisTranslatorJnaImplProvider

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#188]
Tried a book with notes, job 2539, 2540 (562929) to test the bottom of page option. 

Could not manage to produce the book, got the "Validation failed" message.
My guess is that the fallback mechanism does not work with HTML.

I can find more examples if needed.

**Comment by josteinaj** [comment]
This is the error from the log:

```
2018-06-29 17:17:23,755 [DEBUG] com.xmlcalabash.library.DefaultStep - Running {http://code.google.com/p/dotify/}obfl-to-pef !1.19.1.4
2018-06-29 17:17:25,999 [DEBUG] o.d.b.c.BrailleCSSTreeParser_CSSTreeParser - Setting property: hyphens
2018-06-29 17:17:26,000 [DEBUG] o.d.b.c.BrailleCSSTreeParser_CSSTreeParser - Totally added 1 terms
2018-06-29 17:17:26,000 [DEBUG] o.d.b.c.BrailleCSSTreeParser_CSSTreeParser - Returning declaration: hyphens: auto;
.
2018-06-29 17:17:26,000 [DEBUG] o.d.b.c.BrailleCSSTreeParser_CSSTreeParser - Inserted declaration #2 
2018-06-29 17:17:26,009 [ERROR] o.d.p.b.d.c.impl.OBFLToPEFStep - dotify:obfl-to-pef failed
java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException
	at org.daisy.dotify.formatter.impl.page.ScenarioProcessor.invalidateScenario(ScenarioProcessor.java:156) ~[na:na]
	at org.daisy.dotify.formatter.impl.page.ScenarioProcessor.process(ScenarioProcessor.java:62) ~[na:na]
	at org.daisy.dotify.formatter.impl.page.BlockSequence.selectScenario(BlockSequence.java:59) ~[na:na]
	at org.daisy.dotify.formatter.impl.page.PageSequenceBuilder2.<init>(PageSequenceBuilder2.java:93) ~[na:na]
	at org.daisy.dotify.formatter.impl.sheet.SheetDataSource.ensureBuffer(SheetDataSource.java:199) ~[na:na]
	at org.daisy.dotify.formatter.impl.sheet.SheetDataSource.getRemaining(SheetDataSource.java:130) ~[na:na]
	at org.daisy.dotify.formatter.impl.VolumeProvider.prepare(VolumeProvider.java:101) ~[na:na]
	at org.daisy.dotify.formatter.impl.FormatterImpl.getVolumes(FormatterImpl.java:140) ~[na:na]
	at org.daisy.dotify.formatter.impl.FormatterImpl.write(FormatterImpl.java:124) ~[na:na]
	at org.daisy.dotify.formatter.impl.engine.LayoutEngineImpl.convert(LayoutEngineImpl.java:134) ~[na:na]
	at org.daisy.pipeline.braille.dotify.calabash.impl.OBFLToPEFStep.run(OBFLToPEFStep.java:140) ~[na:na]
	at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:389) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XChoose.run(XChoose.java:135) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at com.xmlcalabash.extensions.Eval.run(Eval.java:249) ~[na:na]
	at org.daisy.pipeline.braille.common.calabash.impl.PxTransformStep.run(PxTransformStep.java:143) ~[na:na]
	at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:389) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XChoose.run(XChoose.java:135) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at com.xmlcalabash.runtime.XPipelineCall.run(XPipelineCall.java:94) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XTry.run(XTry.java:98) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:242) ~[na:na]
	at org.daisy.pipeline.job.Job.run(Job.java:216) ~[na:na]
	at org.daisy.pipeline.job.impl.DefaultJobExecutionService$1.run(DefaultJobExecutionService.java:115) ~[na:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
java.lang.ArrayIndexOutOfBoundsException: null
2018-06-29 17:17:26,009 [ERROR] com.xmlcalabash.runtime.XAtomicStep - bundle://75.0:0/xml/transform/dotify-transform.xpl:85:37:java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException
```

**Comment by bertfrees** [comment]
I changed the title as this doesn't seem to have anything to do with the notes fallback.

**Comment by bertfrees** [comment]
It looks like this error may occur when a paragraph contains both hard spaces and words with non-standard hyphenation points. It's a really obvious bug, can't believe we haven't encountered this before.
