### ISSUE TITLE
Braille in EPUB 3 for norwegian translation

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#66]
The default value of the "Braille translator query" option for the "Braille in EPUB 3" script is "(translator:liblouis)". This works. However, if I change it to "(translator:nlb)", it doesn't work.

**Comment by bertfrees** [comment]
Have you tried adding `(grade:[0|1|2|3])`?

**Comment by josteinaj** [comment]
I tried now. Same error:

```
(...)
2017-06-28 10:59:02,601 [DEBUG] com.xmlcalabash.library.DefaultStep - Running {http://www.daisy.org/ns/pipeline/xproc/internal}css-inline !1.10
2017-06-28 10:59:02,616 [DEBUG] com.xmlcalabash - No match for query (input:html)(input:css)(output:html)(output:css)(output:braille)(translator:nlb)(grade:0)(locale:no)
2017-06-28 10:59:02,617 [ERROR] o.d.p.b.c.c.impl.PxTransformStep - px:transform failed
java.lang.RuntimeException: Could not find a Transform for query: (input:html)(input:css)(output:html)(output:css)(output:braille)(translator:nlb)(grade:0)(locale:no)
	at org.daisy.pipeline.braille.common.calabash.impl.PxTransformStep.setup(PxTransformStep.java:93) ~[na:na]
	at org.daisy.pipeline.braille.common.calabash.impl.PxTransformStep.run(PxTransformStep.java:139) ~[na:na]
	at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:389) ~[na:na]
	at com.xmlcalabash.runtime.XForEach.run(XForEach.java:117) ~[na:na]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) ~[na:na]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) ~[na:na]
	at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:242) ~[na:na]
	at org.daisy.pipeline.job.Job.run(Job.java:216) ~[na:na]
	at org.daisy.pipeline.job.impl.DefaultJobExecutionService$1.run(DefaultJobExecutionService.java:113) ~[na:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
2017-06-28 10:59:02,618 [ERROR] com.xmlcalabash - bundle://90.0:1/xml/epub3-to-epub3.xpl:264:40:java.lang.RuntimeException: Could not find a Transform for query: (input:html)(input:css)(output:html)(output:css)(output:braille)(translator:nlb)(grade:0)(locale:no)
(...)
```

**Comment by bertfrees** [comment]
Working on it.

**Comment by bertfrees** [comment]
Pushed a fix.

**Comment by josteinaj** [comment]
Tested locally. Works.
